import type {
  Lead,
  Client,
  Project,
  Invoice,
  Ticket,
  Activity,
} from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Sarah Chen",
    email: "sarah@techflow.io",
    company: "TechFlow Inc",
    phone: "+1 555-0101",
    status: "NEW",
    source: "Website",
    value: 15000,
    createdAt: new Date("2026-03-15"),
  },
  {
    id: "lead-2",
    name: "Marcus Rivera",
    email: "marcus@greenleaf.co",
    company: "GreenLeaf Co",
    phone: "+1 555-0102",
    status: "CONTACTED",
    source: "Referral",
    value: 28000,
    createdAt: new Date("2026-03-12"),
  },
  {
    id: "lead-3",
    name: "Aisha Patel",
    email: "aisha@brightpath.org",
    company: "BrightPath Learning",
    phone: "+1 555-0103",
    status: "QUALIFIED",
    source: "LinkedIn",
    value: 42000,
    createdAt: new Date("2026-03-08"),
  },
  {
    id: "lead-4",
    name: "James Morrison",
    email: "james@cloudnest.dev",
    company: "CloudNest",
    phone: "+1 555-0104",
    status: "PROPOSAL",
    source: "Conference",
    value: 55000,
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "lead-5",
    name: "Elena Volkov",
    email: "elena@datastream.ai",
    company: "DataStream AI",
    status: "CONVERTED",
    source: "Website",
    value: 35000,
    createdAt: new Date("2026-02-20"),
  },
  {
    id: "lead-6",
    name: "Tom Williams",
    email: "tom@oldschool.biz",
    company: "OldSchool Biz",
    status: "LOST",
    source: "Cold outreach",
    notes: "Budget too low",
    value: 8000,
    createdAt: new Date("2026-02-15"),
  },
];

export const mockClients: Client[] = [
  {
    id: "client-1",
    userId: "user-c1",
    company: "DataStream AI",
    email: "elena@datastream.ai",
    phone: "+1 555-0201",
    address: "123 Innovation Dr, San Francisco, CA",
    createdAt: new Date("2026-02-20"),
  },
  {
    id: "client-2",
    userId: "user-c2",
    company: "NovaPay Solutions",
    email: "contact@novapay.com",
    phone: "+1 555-0202",
    address: "456 Finance Ave, New York, NY",
    createdAt: new Date("2026-01-10"),
  },
  {
    id: "client-3",
    userId: "user-c3",
    company: "UrbanPulse",
    email: "team@urbanpulse.app",
    phone: "+1 555-0203",
    createdAt: new Date("2025-11-15"),
  },
  {
    id: "client-4",
    userId: "user-c4",
    company: "MediTrack Health",
    email: "dev@meditrack.io",
    phone: "+1 555-0204",
    address: "789 Health Blvd, Austin, TX",
    createdAt: new Date("2025-09-01"),
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    clientId: "client-1",
    name: "DataStream Dashboard",
    description: "Analytics dashboard SaaS for real-time data monitoring",
    status: "DEVELOPMENT",
    startDate: new Date("2026-02-25"),
    deadline: new Date("2026-05-15"),
    budget: 35000,
    progress: 45,
    createdAt: new Date("2026-02-25"),
  },
  {
    id: "proj-2",
    clientId: "client-2",
    name: "NovaPay Merchant Portal",
    description: "Payment processing portal for small business merchants",
    status: "DESIGN",
    startDate: new Date("2026-03-01"),
    deadline: new Date("2026-06-30"),
    budget: 48000,
    progress: 20,
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "proj-3",
    clientId: "client-3",
    name: "UrbanPulse Mobile App",
    description: "City events and nightlife discovery platform",
    status: "TESTING",
    startDate: new Date("2025-12-01"),
    deadline: new Date("2026-03-30"),
    budget: 32000,
    progress: 78,
    createdAt: new Date("2025-12-01"),
  },
  {
    id: "proj-4",
    clientId: "client-4",
    name: "MediTrack Patient Portal",
    description: "HIPAA-compliant patient management system",
    status: "LAUNCHED",
    startDate: new Date("2025-06-15"),
    deadline: new Date("2025-12-15"),
    budget: 65000,
    progress: 100,
    createdAt: new Date("2025-06-15"),
  },
  {
    id: "proj-5",
    clientId: "client-4",
    name: "MediTrack Scheduling v2",
    description: "AI-powered appointment scheduling add-on",
    status: "DISCOVERY",
    startDate: new Date("2026-03-10"),
    deadline: new Date("2026-07-31"),
    budget: 28000,
    progress: 8,
    createdAt: new Date("2026-03-10"),
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: "inv-1",
    projectId: "proj-1",
    clientId: "client-1",
    amount: 17500,
    status: "SENT",
    description: "DataStream Dashboard - Phase 1 (50% upfront)",
    dueDate: new Date("2026-03-25"),
    createdAt: new Date("2026-02-25"),
  },
  {
    id: "inv-2",
    projectId: "proj-2",
    clientId: "client-2",
    amount: 16000,
    status: "PAID",
    description: "NovaPay Merchant Portal - Discovery & Design deposit",
    dueDate: new Date("2026-03-15"),
    paidAt: new Date("2026-03-10"),
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "inv-3",
    projectId: "proj-3",
    clientId: "client-3",
    amount: 24000,
    status: "PAID",
    description: "UrbanPulse Mobile App - Development milestone",
    dueDate: new Date("2026-02-28"),
    paidAt: new Date("2026-02-26"),
    createdAt: new Date("2026-02-01"),
  },
  {
    id: "inv-4",
    projectId: "proj-4",
    clientId: "client-4",
    amount: 65000,
    status: "PAID",
    description: "MediTrack Patient Portal - Final payment",
    dueDate: new Date("2025-12-30"),
    paidAt: new Date("2025-12-28"),
    createdAt: new Date("2025-12-15"),
  },
  {
    id: "inv-5",
    projectId: "proj-3",
    clientId: "client-3",
    amount: 8000,
    status: "OVERDUE",
    description: "UrbanPulse Mobile App - Testing & QA phase",
    dueDate: new Date("2026-03-10"),
    createdAt: new Date("2026-03-01"),
  },
  {
    id: "inv-6",
    projectId: "proj-5",
    clientId: "client-4",
    amount: 14000,
    status: "DRAFT",
    description: "MediTrack Scheduling v2 - Discovery deposit",
    createdAt: new Date("2026-03-10"),
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "ticket-1",
    clientId: "client-3",
    projectId: "proj-3",
    subject: "Map markers not loading on iOS Safari",
    description:
      "When using Safari on iPhone 15, the map markers in the events view don't appear. Works fine on Chrome.",
    status: "OPEN",
    priority: "HIGH",
    createdAt: new Date("2026-03-16"),
  },
  {
    id: "ticket-2",
    clientId: "client-4",
    projectId: "proj-4",
    subject: "Need to add two new user roles",
    description:
      "We need to add Nurse and Pharmacist roles to the system with specific permissions.",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdAt: new Date("2026-03-14"),
  },
  {
    id: "ticket-3",
    clientId: "client-1",
    projectId: "proj-1",
    subject: "Dashboard export to PDF",
    description:
      "Can we add the ability to export dashboard charts as a PDF report?",
    status: "OPEN",
    priority: "LOW",
    createdAt: new Date("2026-03-12"),
  },
];

export const mockActivities: Activity[] = [
  {
    id: "act-1",
    type: "project_update",
    description: "DataStream Dashboard moved to Development phase",
    entityType: "project",
    entityId: "proj-1",
    userId: "admin-1",
    createdAt: new Date("2026-03-16T14:30:00"),
  },
  {
    id: "act-2",
    type: "invoice_paid",
    description: "NovaPay paid invoice #INV-002 ($16,000)",
    entityType: "invoice",
    entityId: "inv-2",
    userId: "user-c2",
    createdAt: new Date("2026-03-10T09:15:00"),
  },
  {
    id: "act-3",
    type: "ticket_created",
    description: "New ticket: Map markers not loading on iOS Safari",
    entityType: "ticket",
    entityId: "ticket-1",
    userId: "user-c3",
    createdAt: new Date("2026-03-16T11:00:00"),
  },
  {
    id: "act-4",
    type: "lead_created",
    description: "New lead: Sarah Chen from TechFlow Inc",
    entityType: "lead",
    entityId: "lead-1",
    createdAt: new Date("2026-03-15T16:45:00"),
  },
  {
    id: "act-5",
    type: "client_converted",
    description: "Elena Volkov (DataStream AI) converted to client",
    entityType: "client",
    entityId: "client-1",
    createdAt: new Date("2026-02-20T10:00:00"),
  },
];

// Revenue data for charts
export const mockRevenueData = [
  { month: "Oct", revenue: 22000 },
  { month: "Nov", revenue: 18500 },
  { month: "Dec", revenue: 65000 },
  { month: "Jan", revenue: 31000 },
  { month: "Feb", revenue: 41500 },
  { month: "Mar", revenue: 16000 },
];
